name: stitcher
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - numpy<2
  - matplotlib
  - scipy
  - scikit-image
  - pillow
  - pip
  - setuptools
  - wheel
  - requests
  - python-dateutil
  - pip:
      - opencv-python-headless==4.8.1.78
      - auto-py-to-exe==2.46.0
      - bottle==0.13.4
      - bottle-websocket==0.2.9
      - eel==0.18.2
      - gevent==25.5.1
      - gevent-websocket==0.10.1
      - greenlet==3.2.4
      - imagecodecs==2025.3.30
      - imageio==2.37.0
      - importlib-resources==6.5.2
      - networkx==3.5
      - openslide-bin==4.0.0.8
      - openslide-python==1.4.2
      - pyinstaller==6.15.0
      - pyinstaller-hooks-contrib==2025.8
      - pyqt6==6.4.2
      - pyqt6-plugins==6.4.2.2.3
      - pyqt6-qt6==6.4.3
      - pyqt6-sip==13.10.2
      - pyqt6-tools==6.4.2.3.3
      - qt6-applications==6.4.3.2.3
      - qt6-tools==6.4.3.1.3
      - python-dotenv==1.1.1

